-- ============================================================
-- KURLA — GAMME PEAU : COMPLÉTION DU CATALOGUE (B-01)
-- Généré par scripts/generate-skin-range-sql.ts — ne pas éditer à la main.
-- ============================================================
--
-- Constat qui motive cette migration : le catalogue peau publié comptait
-- 3 références (nettoyant, crème, SPF) alors que l'application en recommande
-- 7 (PEAU_KITS) et que les profils de connaissance en citent 7 autres. Quatre
-- produits conseillés n'existaient dans aucune boutique : la recommandation
-- était non achetable par construction.
--
-- Cette migration ajoute 13 fiches « formulation interne » qui complètent
-- les étapes manquantes : exfoliation, niacinamide, acide azélaïque, acide
-- tranexamique, vitamine C stabilisée, rétinol doux, hydratation légère, soin
-- local, SPF teinté, masque apaisant. Chacune des six préoccupations (acné,
-- taches, sécheresse, sensibilité, maturité, éclat) dispose désormais d'une
-- routine complète nettoyant → traitement → SPF.
--
-- Points de vérité, volontairement non enjolivés :
--   · image_ownership_status = 'illustrative' : ces visuels sont des
--     illustrations, pas des packshots. Le produit n'est pas fabriqué, aucun
--     visuel officiel n'existe. 'brand_provided' aurait été un mensonge.
--   · *_validation_status = 'pending' : rien n'a été vérifié. Une formule
--     cible n'est pas une formule contrôlée.
--   · stock_quantity = 0 et in_stock = TRUE, badges = ['preorder'] : même
--     régime que les 67 autres produits publiés, en attente du premier lot.
--
-- Idempotent : ON CONFLICT (id) DO UPDATE. Rejouable sans dommage.
-- ============================================================

INSERT INTO public.products (
    id, slug, name, brand, price, category, subcategory, description, image_url, inci, ingredients, skin_types, concerns, country_availability, is_active, catalog_status, is_preorder, badges, stock_quantity, in_stock, source_supplier, supplier_id, routine_step, size_label, texture, usage_frequency, benefit_primary, for_who, not_ideal_if, how_to_use, fragrance, contains_fragrance, vat_rate, price_includes_vat, warnings, brand_verification_status, image_ownership_status, ingredient_verification_status, claims_validation_status, images_validation_status, stock_validation_status, certifications_validation_status, translations_validation_status, minor_safety_status, image_supervision_status
  ) VALUES (
    'peau-ess-004',
    'eau-micellaire-apaisante-sans-parfum-200ml',
    'Eau Micellaire Apaisante Sans Parfum — 200ml',
    'KURLA Skincare',
    11.90,
    'peau',
    'Nettoyage',
    '[PRÉCOMMANDE — expédié sous 30 jours maximum] Nettoyage sans rinçage, sans parfum ni alcool : les micelles captent maquillage et filtres solaires sans décoller la barrière cutanée. Panthénol et allantoïne limitent l’échauffement après le passage du coton, ce qui compte sur les peaux réactives.',
    'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=800&q=80',
    'Aqua, Glycerin, Polyglyceryl-4 Caprate, Panthenol, Allantoin, Bisabolol, Sodium Benzoate, Citric Acid',
    ARRAY['Glycérine Végétale', 'Panthénol', 'Allantoïne', 'Bisabolol']::TEXT[],
    ARRAY['mixte', 'seche', 'sensible']::TEXT[],
    ARRAY['hydrater_peau', 'peau_sensible']::TEXT[],
    ARRAY['FR', 'BE', 'DOM', 'INT']::TEXT[],
    TRUE,
    'published',
    TRUE,
    ARRAY['preorder', 'sans-parfum']::TEXT[],
    0,
    TRUE,
    'KURLA Skincare — formulation interne (précommande)',
    'sup-brands-wholesale',
    'Nettoyant doux',
    '200ml',
    'Liquide aqueux, aucun film après passage',
    'Matin et soir',
    'Démaquille et nettoie sans frotter ni décapper',
    'Peaux sensibles, réactives ou sèches ; yeux sensibles ; routines doubles nettoyages.',
    'Maquillage très couvrant ou SPF résistant à l’eau : préférer un démaquillage huileux.',
    'Imbiber un coton, passer sans frotter, renouveler jusqu’à ce que le coton reste propre. Sans rinçage. Peut précéder le gel nettoyant le soir en cas de SPF ou de maquillage.',
    'Sans parfum ajouté',
    FALSE,
    20.00,
    TRUE,
    ARRAY[]::TEXT[],
    'verified',
    'illustrative',
    'pending',
    'pending',
    'pending',
    'pending',
    'pending',
    'pending',
    'not_provided',
    'not_provided'
  )
  ON CONFLICT (id) DO UPDATE SET
    slug = EXCLUDED.slug,
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    price = EXCLUDED.price,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    description = EXCLUDED.description,
    image_url = EXCLUDED.image_url,
    inci = EXCLUDED.inci,
    ingredients = EXCLUDED.ingredients,
    skin_types = EXCLUDED.skin_types,
    concerns = EXCLUDED.concerns,
    country_availability = EXCLUDED.country_availability,
    is_active = EXCLUDED.is_active,
    catalog_status = EXCLUDED.catalog_status,
    is_preorder = EXCLUDED.is_preorder,
    badges = EXCLUDED.badges,
    stock_quantity = EXCLUDED.stock_quantity,
    in_stock = EXCLUDED.in_stock,
    source_supplier = EXCLUDED.source_supplier,
    supplier_id = EXCLUDED.supplier_id,
    routine_step = EXCLUDED.routine_step,
    size_label = EXCLUDED.size_label,
    texture = EXCLUDED.texture,
    usage_frequency = EXCLUDED.usage_frequency,
    benefit_primary = EXCLUDED.benefit_primary,
    for_who = EXCLUDED.for_who,
    not_ideal_if = EXCLUDED.not_ideal_if,
    how_to_use = EXCLUDED.how_to_use,
    fragrance = EXCLUDED.fragrance,
    contains_fragrance = EXCLUDED.contains_fragrance,
    vat_rate = EXCLUDED.vat_rate,
    price_includes_vat = EXCLUDED.price_includes_vat,
    warnings = EXCLUDED.warnings,
    brand_verification_status = EXCLUDED.brand_verification_status,
    image_ownership_status = EXCLUDED.image_ownership_status,
    ingredient_verification_status = EXCLUDED.ingredient_verification_status,
    claims_validation_status = EXCLUDED.claims_validation_status,
    images_validation_status = EXCLUDED.images_validation_status,
    stock_validation_status = EXCLUDED.stock_validation_status,
    certifications_validation_status = EXCLUDED.certifications_validation_status,
    translations_validation_status = EXCLUDED.translations_validation_status,
    minor_safety_status = EXCLUDED.minor_safety_status,
    image_supervision_status = EXCLUDED.image_supervision_status;

INSERT INTO public.products (
    id, slug, name, brand, price, category, subcategory, description, image_url, inci, ingredients, skin_types, concerns, country_availability, is_active, catalog_status, is_preorder, badges, stock_quantity, in_stock, source_supplier, supplier_id, routine_step, size_label, texture, usage_frequency, benefit_primary, for_who, not_ideal_if, how_to_use, fragrance, contains_fragrance, vat_rate, price_includes_vat, warnings, brand_verification_status, image_ownership_status, ingredient_verification_status, claims_validation_status, images_validation_status, stock_validation_status, certifications_validation_status, translations_validation_status, minor_safety_status, image_supervision_status
  ) VALUES (
    'peau-ess-005',
    'exfoliant-aha-bha-1x-semaine-30ml',
    'Exfoliant AHA/BHA 1×/semaine — 30ml',
    'KURLA Skincare',
    17.90,
    'peau',
    'Exfoliation',
    '[PRÉCOMMANDE — expédié sous 30 jours maximum] Glycolique et lactique travaillent en surface, l’acide salicylique dégage le pore. Sur peau mélaninée, l’enjeu n’est pas la puissance mais la retenue : une exfoliation agressive déclenche une inflammation, et l’inflammation est précisément ce qui fabrique les taches. Une fois par semaine, pas davantage.',
    'https://images.unsplash.com/photo-1608248540480-17637841852d?auto=format&fit=crop&w=800&q=80',
    'Aqua, Glycolic Acid, Lactic Acid, Salicylic Acid, Glycerin, Panthenol, Sodium Hydroxide, Allantoin, Xanthan Gum, Phenoxyethanol',
    ARRAY['Acide Glycolique', 'Acide Lactique', 'Acide Salicylique', 'Panthénol']::TEXT[],
    ARRAY['mixte', 'grasse']::TEXT[],
    ARRAY['eclat_teint_terne', 'taches_hyperpigmentation', 'imperfections_acne']::TEXT[],
    ARRAY['FR', 'BE', 'DOM', 'INT']::TEXT[],
    TRUE,
    'published',
    TRUE,
    ARRAY['preorder', 'sans-parfum', 'actif-doux']::TEXT[],
    0,
    TRUE,
    'KURLA Skincare — formulation interne (précommande)',
    'sup-brands-wholesale',
    'Exfoliant doux',
    '30ml',
    'Liquide fluide, absorption rapide',
    'Une fois par semaine, le soir',
    'Désépaissit le grain et atténue les marques en surface',
    'Grain irrégulier, marques post-imperfections, teint terne, pores visibles.',
    'Peau sensible ou irritée, barrière abîmée, grossesse (acide salicylique), avant une exposition solaire.',
    'Le soir, sur peau sèche et propre. Attendre 10 minutes avant le sérum hydratant. Ne jamais associer le même soir au rétinol ou à la vitamine C. SPF 50 obligatoire le lendemain.',
    'Sans parfum ajouté',
    FALSE,
    20.00,
    TRUE,
    ARRAY['Actif exfoliant : une fois par semaine au départ, jamais le même soir qu’un rétinol. Photosensibilisant — SPF 50 quotidien indispensable.']::TEXT[],
    'verified',
    'illustrative',
    'pending',
    'pending',
    'pending',
    'pending',
    'pending',
    'pending',
    'not_provided',
    'not_provided'
  )
  ON CONFLICT (id) DO UPDATE SET
    slug = EXCLUDED.slug,
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    price = EXCLUDED.price,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    description = EXCLUDED.description,
    image_url = EXCLUDED.image_url,
    inci = EXCLUDED.inci,
    ingredients = EXCLUDED.ingredients,
    skin_types = EXCLUDED.skin_types,
    concerns = EXCLUDED.concerns,
    country_availability = EXCLUDED.country_availability,
    is_active = EXCLUDED.is_active,
    catalog_status = EXCLUDED.catalog_status,
    is_preorder = EXCLUDED.is_preorder,
    badges = EXCLUDED.badges,
    stock_quantity = EXCLUDED.stock_quantity,
    in_stock = EXCLUDED.in_stock,
    source_supplier = EXCLUDED.source_supplier,
    supplier_id = EXCLUDED.supplier_id,
    routine_step = EXCLUDED.routine_step,
    size_label = EXCLUDED.size_label,
    texture = EXCLUDED.texture,
    usage_frequency = EXCLUDED.usage_frequency,
    benefit_primary = EXCLUDED.benefit_primary,
    for_who = EXCLUDED.for_who,
    not_ideal_if = EXCLUDED.not_ideal_if,
    how_to_use = EXCLUDED.how_to_use,
    fragrance = EXCLUDED.fragrance,
    contains_fragrance = EXCLUDED.contains_fragrance,
    vat_rate = EXCLUDED.vat_rate,
    price_includes_vat = EXCLUDED.price_includes_vat,
    warnings = EXCLUDED.warnings,
    brand_verification_status = EXCLUDED.brand_verification_status,
    image_ownership_status = EXCLUDED.image_ownership_status,
    ingredient_verification_status = EXCLUDED.ingredient_verification_status,
    claims_validation_status = EXCLUDED.claims_validation_status,
    images_validation_status = EXCLUDED.images_validation_status,
    stock_validation_status = EXCLUDED.stock_validation_status,
    certifications_validation_status = EXCLUDED.certifications_validation_status,
    translations_validation_status = EXCLUDED.translations_validation_status,
    minor_safety_status = EXCLUDED.minor_safety_status,
    image_supervision_status = EXCLUDED.image_supervision_status;

INSERT INTO public.products (
    id, slug, name, brand, price, category, subcategory, description, image_url, inci, ingredients, skin_types, concerns, country_availability, is_active, catalog_status, is_preorder, badges, stock_quantity, in_stock, source_supplier, supplier_id, routine_step, size_label, texture, usage_frequency, benefit_primary, for_who, not_ideal_if, how_to_use, fragrance, contains_fragrance, vat_rate, price_includes_vat, warnings, brand_verification_status, image_ownership_status, ingredient_verification_status, claims_validation_status, images_validation_status, stock_validation_status, certifications_validation_status, translations_validation_status, minor_safety_status, image_supervision_status
  ) VALUES (
    'peau-ess-006',
    'serum-niacinamide-5-30ml',
    'Sérum Niacinamide 5% — 30ml',
    'KURLA Skincare',
    15.90,
    'peau',
    'Traitement',
    '[PRÉCOMMANDE — expédié sous 30 jours maximum] La niacinamide à 5 % — volontairement sous les 10 % courants, mieux tolérés par les peaux réactives — associée au zinc, qui régule l’excès de sébum. C’est l’actif le mieux documenté sur les peaux riches en mélanine pour les marques post-inflammatoires, sans photosensibilisation.',
    'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80',
    'Aqua, Niacinamide, Glycerin, Zinc PCA, Panthenol, Betaine, Sodium Hyaluronate, Xanthan Gum, Phenoxyethanol',
    ARRAY['Niacinamide 5%', 'Zinc PCA', 'Panthénol', 'Bétaïne']::TEXT[],
    ARRAY['mixte', 'grasse', 'sensible']::TEXT[],
    ARRAY['imperfections_acne', 'taches_hyperpigmentation', 'eclat_teint_terne']::TEXT[],
    ARRAY['FR', 'BE', 'DOM', 'INT']::TEXT[],
    TRUE,
    'published',
    TRUE,
    ARRAY['preorder', 'sans-parfum']::TEXT[],
    0,
    TRUE,
    'KURLA Skincare — formulation interne (précommande)',
    'sup-brands-wholesale',
    'Sérum niacinamide',
    '30ml',
    'Sérum aqueux léger, fini non gras',
    'Matin et soir',
    'Apaise les imperfections et resserre le grain',
    'Imperfections, pores visibles, brillance, marques post-acné, peaux qui supportent mal les acides.',
    'Aucune contre-indication particulière ; une sensation de picotement passagère est possible.',
    '3 à 4 gouttes sur peau propre et légèrement humide, avant la crème. Matin et soir. Compatible avec tous les autres actifs de la gamme.',
    'Sans parfum ajouté',
    FALSE,
    20.00,
    TRUE,
    ARRAY[]::TEXT[],
    'verified',
    'illustrative',
    'pending',
    'pending',
    'pending',
    'pending',
    'pending',
    'pending',
    'not_provided',
    'not_provided'
  )
  ON CONFLICT (id) DO UPDATE SET
    slug = EXCLUDED.slug,
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    price = EXCLUDED.price,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    description = EXCLUDED.description,
    image_url = EXCLUDED.image_url,
    inci = EXCLUDED.inci,
    ingredients = EXCLUDED.ingredients,
    skin_types = EXCLUDED.skin_types,
    concerns = EXCLUDED.concerns,
    country_availability = EXCLUDED.country_availability,
    is_active = EXCLUDED.is_active,
    catalog_status = EXCLUDED.catalog_status,
    is_preorder = EXCLUDED.is_preorder,
    badges = EXCLUDED.badges,
    stock_quantity = EXCLUDED.stock_quantity,
    in_stock = EXCLUDED.in_stock,
    source_supplier = EXCLUDED.source_supplier,
    supplier_id = EXCLUDED.supplier_id,
    routine_step = EXCLUDED.routine_step,
    size_label = EXCLUDED.size_label,
    texture = EXCLUDED.texture,
    usage_frequency = EXCLUDED.usage_frequency,
    benefit_primary = EXCLUDED.benefit_primary,
    for_who = EXCLUDED.for_who,
    not_ideal_if = EXCLUDED.not_ideal_if,
    how_to_use = EXCLUDED.how_to_use,
    fragrance = EXCLUDED.fragrance,
    contains_fragrance = EXCLUDED.contains_fragrance,
    vat_rate = EXCLUDED.vat_rate,
    price_includes_vat = EXCLUDED.price_includes_vat,
    warnings = EXCLUDED.warnings,
    brand_verification_status = EXCLUDED.brand_verification_status,
    image_ownership_status = EXCLUDED.image_ownership_status,
    ingredient_verification_status = EXCLUDED.ingredient_verification_status,
    claims_validation_status = EXCLUDED.claims_validation_status,
    images_validation_status = EXCLUDED.images_validation_status,
    stock_validation_status = EXCLUDED.stock_validation_status,
    certifications_validation_status = EXCLUDED.certifications_validation_status,
    translations_validation_status = EXCLUDED.translations_validation_status,
    minor_safety_status = EXCLUDED.minor_safety_status,
    image_supervision_status = EXCLUDED.image_supervision_status;

INSERT INTO public.products (
    id, slug, name, brand, price, category, subcategory, description, image_url, inci, ingredients, skin_types, concerns, country_availability, is_active, catalog_status, is_preorder, badges, stock_quantity, in_stock, source_supplier, supplier_id, routine_step, size_label, texture, usage_frequency, benefit_primary, for_who, not_ideal_if, how_to_use, fragrance, contains_fragrance, vat_rate, price_includes_vat, warnings, brand_verification_status, image_ownership_status, ingredient_verification_status, claims_validation_status, images_validation_status, stock_validation_status, certifications_validation_status, translations_validation_status, minor_safety_status, image_supervision_status
  ) VALUES (
    'peau-ess-007',
    'serum-acide-azelaique-10-30ml',
    'Sérum Acide Azélaïque 10% — 30ml',
    'KURLA Skincare',
    18.90,
    'peau',
    'Traitement',
    '[PRÉCOMMANDE — expédié sous 30 jours maximum] L’acide azélaïque cumule trois effets utiles sur les peaux mélaninées : il calme l’inflammation des boutons, il freine la production de mélanine (donc les marques qui suivent) et il n’est pas photosensibilisant. C’est l’actif le plus sûr quand il faut agir sans abîmer.',
    'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=800&q=80',
    'Aqua, Azelaic Acid, Glycerin, Propanediol, Squalane, Niacinamide, Panthenol, Xanthan Gum, Phenoxyethanol',
    ARRAY['Acide Azélaïque 10%', 'Squalane Végétal', 'Niacinamide', 'Panthénol']::TEXT[],
    ARRAY['mixte', 'grasse', 'sensible', 'seche']::TEXT[],
    ARRAY['imperfections_acne', 'taches_hyperpigmentation', 'peau_sensible']::TEXT[],
    ARRAY['FR', 'BE', 'DOM', 'INT']::TEXT[],
    TRUE,
    'published',
    TRUE,
    ARRAY['preorder', 'sans-parfum']::TEXT[],
    0,
    TRUE,
    'KURLA Skincare — formulation interne (précommande)',
    'sup-brands-wholesale',
    'Sérum acide azélaïque',
    '30ml',
    'Sérum-crème, fini naturel',
    'Matin et soir',
    'Imperfections et marques pigmentaires, sans irritation',
    'Imperfections associées à des marques, rougeurs, peaux sensibles qui ne tolèrent pas les acides exfoliants.',
    'Peau très réactive en poussée : introduire un soir sur deux pendant deux semaines.',
    'Une noisette sur peau propre, matin et soir, avant la crème. Peut s’utiliser sur l’ensemble du visage ou en local. Pas de contre-indication avec le SPF.',
    'Sans parfum ajouté',
    FALSE,
    20.00,
    TRUE,
    ARRAY[]::TEXT[],
    'verified',
    'illustrative',
    'pending',
    'pending',
    'pending',
    'pending',
    'pending',
    'pending',
    'not_provided',
    'not_provided'
  )
  ON CONFLICT (id) DO UPDATE SET
    slug = EXCLUDED.slug,
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    price = EXCLUDED.price,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    description = EXCLUDED.description,
    image_url = EXCLUDED.image_url,
    inci = EXCLUDED.inci,
    ingredients = EXCLUDED.ingredients,
    skin_types = EXCLUDED.skin_types,
    concerns = EXCLUDED.concerns,
    country_availability = EXCLUDED.country_availability,
    is_active = EXCLUDED.is_active,
    catalog_status = EXCLUDED.catalog_status,
    is_preorder = EXCLUDED.is_preorder,
    badges = EXCLUDED.badges,
    stock_quantity = EXCLUDED.stock_quantity,
    in_stock = EXCLUDED.in_stock,
    source_supplier = EXCLUDED.source_supplier,
    supplier_id = EXCLUDED.supplier_id,
    routine_step = EXCLUDED.routine_step,
    size_label = EXCLUDED.size_label,
    texture = EXCLUDED.texture,
    usage_frequency = EXCLUDED.usage_frequency,
    benefit_primary = EXCLUDED.benefit_primary,
    for_who = EXCLUDED.for_who,
    not_ideal_if = EXCLUDED.not_ideal_if,
    how_to_use = EXCLUDED.how_to_use,
    fragrance = EXCLUDED.fragrance,
    contains_fragrance = EXCLUDED.contains_fragrance,
    vat_rate = EXCLUDED.vat_rate,
    price_includes_vat = EXCLUDED.price_includes_vat,
    warnings = EXCLUDED.warnings,
    brand_verification_status = EXCLUDED.brand_verification_status,
    image_ownership_status = EXCLUDED.image_ownership_status,
    ingredient_verification_status = EXCLUDED.ingredient_verification_status,
    claims_validation_status = EXCLUDED.claims_validation_status,
    images_validation_status = EXCLUDED.images_validation_status,
    stock_validation_status = EXCLUDED.stock_validation_status,
    certifications_validation_status = EXCLUDED.certifications_validation_status,
    translations_validation_status = EXCLUDED.translations_validation_status,
    minor_safety_status = EXCLUDED.minor_safety_status,
    image_supervision_status = EXCLUDED.image_supervision_status;

INSERT INTO public.products (
    id, slug, name, brand, price, category, subcategory, description, image_url, inci, ingredients, skin_types, concerns, country_availability, is_active, catalog_status, is_preorder, badges, stock_quantity, in_stock, source_supplier, supplier_id, routine_step, size_label, texture, usage_frequency, benefit_primary, for_who, not_ideal_if, how_to_use, fragrance, contains_fragrance, vat_rate, price_includes_vat, warnings, brand_verification_status, image_ownership_status, ingredient_verification_status, claims_validation_status, images_validation_status, stock_validation_status, certifications_validation_status, translations_validation_status, minor_safety_status, image_supervision_status
  ) VALUES (
    'peau-ess-008',
    'serum-acide-tranexamique-3-alpha-arbutine-2-30ml',
    'Sérum Acide Tranexamique 3% + Alpha-Arbutine 2% — 30ml',
    'KURLA Skincare',
    24.90,
    'peau',
    'Éclat & Uniformité',
    '[PRÉCOMMANDE — expédié sous 30 jours maximum] L’acide tranexamique agit en amont de la tache, sur le signal qui déclenche la production de mélanine ; l’alpha-arbutine ralentit l’enzyme qui la fabrique. Ce couple travaille là où l’hydroquinone — interdite en cosmétique en Europe — n’est pas une option, et sans la photosensibilisation des acides exfoliants.',
    'https://images.unsplash.com/photo-1608248597261-e4d09123fe1c?auto=format&fit=crop&w=800&q=80',
    'Aqua, Tranexamic Acid, Alpha-Arbutin, Glycerin, Niacinamide, Sodium Hyaluronate, Panthenol, Glycyrrhiza Glabra Root Extract, Xanthan Gum, Phenoxyethanol',
    ARRAY['Acide Tranexamique 3%', 'Alpha-Arbutine 2%', 'Extrait de Réglisse', 'Niacinamide']::TEXT[],
    ARRAY['mixte', 'grasse', 'seche', 'sensible']::TEXT[],
    ARRAY['taches_hyperpigmentation', 'eclat_teint_terne']::TEXT[],
    ARRAY['FR', 'BE', 'DOM', 'INT']::TEXT[],
    TRUE,
    'published',
    TRUE,
    ARRAY['preorder', 'sans-parfum']::TEXT[],
    0,
    TRUE,
    'KURLA Skincare — formulation interne (précommande)',
    'sup-brands-wholesale',
    'Sérum anti-taches',
    '30ml',
    'Sérum fluide, fini mat',
    'Matin et soir',
    'Atténue les taches installées sans agresser',
    'Taches installées, marques post-imperfections persistantes, teint non uniforme.',
    'Aucune contre-indication ; sans effet sur les taches très anciennes et profondes, qui relèvent d’un avis dermatologique.',
    '4 gouttes matin et soir sur peau propre, sur l’ensemble du visage ou sur les zones marquées. Les résultats se mesurent en semaines, pas en jours : compter 8 à 12 semaines.',
    'Sans parfum ajouté',
    FALSE,
    20.00,
    TRUE,
    ARRAY['Les résultats sont progressifs : 8 à 12 semaines d’usage régulier. Une tache qui change d’aspect, de taille ou de couleur relève d’un avis médical, pas d’un soin.']::TEXT[],
    'verified',
    'illustrative',
    'pending',
    'pending',
    'pending',
    'pending',
    'pending',
    'pending',
    'not_provided',
    'not_provided'
  )
  ON CONFLICT (id) DO UPDATE SET
    slug = EXCLUDED.slug,
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    price = EXCLUDED.price,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    description = EXCLUDED.description,
    image_url = EXCLUDED.image_url,
    inci = EXCLUDED.inci,
    ingredients = EXCLUDED.ingredients,
    skin_types = EXCLUDED.skin_types,
    concerns = EXCLUDED.concerns,
    country_availability = EXCLUDED.country_availability,
    is_active = EXCLUDED.is_active,
    catalog_status = EXCLUDED.catalog_status,
    is_preorder = EXCLUDED.is_preorder,
    badges = EXCLUDED.badges,
    stock_quantity = EXCLUDED.stock_quantity,
    in_stock = EXCLUDED.in_stock,
    source_supplier = EXCLUDED.source_supplier,
    supplier_id = EXCLUDED.supplier_id,
    routine_step = EXCLUDED.routine_step,
    size_label = EXCLUDED.size_label,
    texture = EXCLUDED.texture,
    usage_frequency = EXCLUDED.usage_frequency,
    benefit_primary = EXCLUDED.benefit_primary,
    for_who = EXCLUDED.for_who,
    not_ideal_if = EXCLUDED.not_ideal_if,
    how_to_use = EXCLUDED.how_to_use,
    fragrance = EXCLUDED.fragrance,
    contains_fragrance = EXCLUDED.contains_fragrance,
    vat_rate = EXCLUDED.vat_rate,
    price_includes_vat = EXCLUDED.price_includes_vat,
    warnings = EXCLUDED.warnings,
    brand_verification_status = EXCLUDED.brand_verification_status,
    image_ownership_status = EXCLUDED.image_ownership_status,
    ingredient_verification_status = EXCLUDED.ingredient_verification_status,
    claims_validation_status = EXCLUDED.claims_validation_status,
    images_validation_status = EXCLUDED.images_validation_status,
    stock_validation_status = EXCLUDED.stock_validation_status,
    certifications_validation_status = EXCLUDED.certifications_validation_status,
    translations_validation_status = EXCLUDED.translations_validation_status,
    minor_safety_status = EXCLUDED.minor_safety_status,
    image_supervision_status = EXCLUDED.image_supervision_status;

INSERT INTO public.products (
    id, slug, name, brand, price, category, subcategory, description, image_url, inci, ingredients, skin_types, concerns, country_availability, is_active, catalog_status, is_preorder, badges, stock_quantity, in_stock, source_supplier, supplier_id, routine_step, size_label, texture, usage_frequency, benefit_primary, for_who, not_ideal_if, how_to_use, fragrance, contains_fragrance, vat_rate, price_includes_vat, warnings, brand_verification_status, image_ownership_status, ingredient_verification_status, claims_validation_status, images_validation_status, stock_validation_status, certifications_validation_status, translations_validation_status, minor_safety_status, image_supervision_status
  ) VALUES (
    'peau-ess-009',
    'serum-vitamine-c-stabilisee-10-30ml',
    'Sérum Vitamine C Stabilisée 10% — 30ml',
    'KURLA Skincare',
    22.90,
    'peau',
    'Éclat & Uniformité',
    '[PRÉCOMMANDE — expédié sous 30 jours maximum] Forme stabilisée de vitamine C (3-O-éthyl ascorbique), qui ne s’oxyde pas à la lumière comme l’acide ascorbique pur — un point décisif pour un produit vendu en flacon transparent. Associée à l’acide férulique et à la vitamine E, elle renforce l’action du SPF contre les UV, ce qui est la vraie raison de la mettre le matin.',
    'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=800&q=80',
    'Aqua, 3-O-Ethyl Ascorbic Acid, Glycerin, Ferulic Acid, Tocopherol, Sodium Hyaluronate, Panthenol, Sodium Metabisulfite, Xanthan Gum, Phenoxyethanol',
    ARRAY['Vitamine C Stabilisée 10%', 'Acide Férulique', 'Vitamine E', 'Acide Hyaluronique']::TEXT[],
    ARRAY['mixte', 'grasse', 'normale']::TEXT[],
    ARRAY['eclat_teint_terne', 'taches_hyperpigmentation', 'maturite_rides']::TEXT[],
    ARRAY['FR', 'BE', 'DOM', 'INT']::TEXT[],
    TRUE,
    'published',
    TRUE,
    ARRAY['preorder', 'sans-parfum']::TEXT[],
    0,
    TRUE,
    'KURLA Skincare — formulation interne (précommande)',
    'sup-brands-wholesale',
    'Sérum vitamine C',
    '30ml',
    'Sérum aqueux, fini sec',
    'Le matin',
    'Éclat, teint uniforme, antioxydant sous le SPF',
    'Teint terne, manque d’éclat, teint non uniforme, exposition urbaine et solaire.',
    'Peau irritée ou barrière abîmée : attendre la réparation avant d’introduire un antioxydant acide.',
    '4 gouttes le matin, sur peau propre et sèche, avant la crème et le SPF. Introduire un matin sur deux la première semaine. À conserver à l’abri de la lumière.',
    'Sans parfum ajouté',
    FALSE,
    20.00,
    TRUE,
    ARRAY['Le matin uniquement, toujours suivi d’un SPF 50. Une légère sensation de picotement à l’application est fréquente les premiers jours.']::TEXT[],
    'verified',
    'illustrative',
    'pending',
    'pending',
    'pending',
    'pending',
    'pending',
    'pending',
    'not_provided',
    'not_provided'
  )
  ON CONFLICT (id) DO UPDATE SET
    slug = EXCLUDED.slug,
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    price = EXCLUDED.price,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    description = EXCLUDED.description,
    image_url = EXCLUDED.image_url,
    inci = EXCLUDED.inci,
    ingredients = EXCLUDED.ingredients,
    skin_types = EXCLUDED.skin_types,
    concerns = EXCLUDED.concerns,
    country_availability = EXCLUDED.country_availability,
    is_active = EXCLUDED.is_active,
    catalog_status = EXCLUDED.catalog_status,
    is_preorder = EXCLUDED.is_preorder,
    badges = EXCLUDED.badges,
    stock_quantity = EXCLUDED.stock_quantity,
    in_stock = EXCLUDED.in_stock,
    source_supplier = EXCLUDED.source_supplier,
    supplier_id = EXCLUDED.supplier_id,
    routine_step = EXCLUDED.routine_step,
    size_label = EXCLUDED.size_label,
    texture = EXCLUDED.texture,
    usage_frequency = EXCLUDED.usage_frequency,
    benefit_primary = EXCLUDED.benefit_primary,
    for_who = EXCLUDED.for_who,
    not_ideal_if = EXCLUDED.not_ideal_if,
    how_to_use = EXCLUDED.how_to_use,
    fragrance = EXCLUDED.fragrance,
    contains_fragrance = EXCLUDED.contains_fragrance,
    vat_rate = EXCLUDED.vat_rate,
    price_includes_vat = EXCLUDED.price_includes_vat,
    warnings = EXCLUDED.warnings,
    brand_verification_status = EXCLUDED.brand_verification_status,
    image_ownership_status = EXCLUDED.image_ownership_status,
    ingredient_verification_status = EXCLUDED.ingredient_verification_status,
    claims_validation_status = EXCLUDED.claims_validation_status,
    images_validation_status = EXCLUDED.images_validation_status,
    stock_validation_status = EXCLUDED.stock_validation_status,
    certifications_validation_status = EXCLUDED.certifications_validation_status,
    translations_validation_status = EXCLUDED.translations_validation_status,
    minor_safety_status = EXCLUDED.minor_safety_status,
    image_supervision_status = EXCLUDED.image_supervision_status;

INSERT INTO public.products (
    id, slug, name, brand, price, category, subcategory, description, image_url, inci, ingredients, skin_types, concerns, country_availability, is_active, catalog_status, is_preorder, badges, stock_quantity, in_stock, source_supplier, supplier_id, routine_step, size_label, texture, usage_frequency, benefit_primary, for_who, not_ideal_if, how_to_use, fragrance, contains_fragrance, vat_rate, price_includes_vat, warnings, brand_verification_status, image_ownership_status, ingredient_verification_status, claims_validation_status, images_validation_status, stock_validation_status, certifications_validation_status, translations_validation_status, minor_safety_status, image_supervision_status
  ) VALUES (
    'peau-ess-010',
    'serum-retinol-doux-03-capsule-30ml',
    'Sérum Rétinol Doux 0,3% Capsulé — 30ml',
    'KURLA Skincare',
    26.90,
    'peau',
    'Traitement',
    '[PRÉCOMMANDE — expédié sous 30 jours maximum] Rétinol encapsulé : la libération est lente, ce qui réduit les picotements et la desquamation sans renoncer à l’effet. Le dosage à 0,3 % est un dosage d’entrée, pas un dosage d’entretien — c’est délibéré, la majorité des abandons de rétinol viennent d’une montée trop rapide.',
    'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=800&q=80',
    'Aqua, Glycerin, Caprylic/Capric Triglyceride, Retinol, Hydroxypinacolone Retinoate, Ceramide NP, Squalane, Tocopherol, Polysorbate 20, Phenoxyethanol',
    ARRAY['Rétinol Encapsulé 0,3%', 'Céramides NP', 'Squalane Végétal', 'Vitamine E']::TEXT[],
    ARRAY['mixte', 'grasse', 'normale', 'seche']::TEXT[],
    ARRAY['maturite_rides', 'taches_hyperpigmentation', 'imperfections_acne']::TEXT[],
    ARRAY['FR', 'BE', 'DOM', 'INT']::TEXT[],
    TRUE,
    'published',
    TRUE,
    ARRAY['preorder', 'sans-parfum', 'actif-doux']::TEXT[],
    0,
    TRUE,
    'KURLA Skincare — formulation interne (précommande)',
    'sup-brands-wholesale',
    'Sérum rétinol doux',
    '30ml',
    'Sérum-crème onctueux, fini confortable',
    'Le soir, 2 soirs par semaine au départ',
    'Rides, grain, marques — avec une tolérance progressive',
    'Rides et ridules, grain irrégulier, marques pigmentaires installées, imperfections persistantes.',
    'Grossesse et allaitement (contre-indication absolue). Peau sensible en poussée. À ne jamais associer le même soir à un exfoliant AHA/BHA.',
    'Le soir uniquement, sur peau sèche, 2 soirs par semaine pendant 3 semaines, puis augmenter d’un soir toutes les 3 semaines selon tolérance. Hydrater généreusement. SPF 50 impératif chaque matin.',
    'Sans parfum ajouté',
    FALSE,
    20.00,
    TRUE,
    ARRAY['Contre-indiqué pendant la grossesse et l’allaitement. Le soir uniquement, jamais le même soir qu’un AHA/BHA. Desquamation possible les premières semaines : espacer les applications plutôt qu’arrêter.']::TEXT[],
    'verified',
    'illustrative',
    'pending',
    'pending',
    'pending',
    'pending',
    'pending',
    'pending',
    'not_provided',
    'not_provided'
  )
  ON CONFLICT (id) DO UPDATE SET
    slug = EXCLUDED.slug,
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    price = EXCLUDED.price,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    description = EXCLUDED.description,
    image_url = EXCLUDED.image_url,
    inci = EXCLUDED.inci,
    ingredients = EXCLUDED.ingredients,
    skin_types = EXCLUDED.skin_types,
    concerns = EXCLUDED.concerns,
    country_availability = EXCLUDED.country_availability,
    is_active = EXCLUDED.is_active,
    catalog_status = EXCLUDED.catalog_status,
    is_preorder = EXCLUDED.is_preorder,
    badges = EXCLUDED.badges,
    stock_quantity = EXCLUDED.stock_quantity,
    in_stock = EXCLUDED.in_stock,
    source_supplier = EXCLUDED.source_supplier,
    supplier_id = EXCLUDED.supplier_id,
    routine_step = EXCLUDED.routine_step,
    size_label = EXCLUDED.size_label,
    texture = EXCLUDED.texture,
    usage_frequency = EXCLUDED.usage_frequency,
    benefit_primary = EXCLUDED.benefit_primary,
    for_who = EXCLUDED.for_who,
    not_ideal_if = EXCLUDED.not_ideal_if,
    how_to_use = EXCLUDED.how_to_use,
    fragrance = EXCLUDED.fragrance,
    contains_fragrance = EXCLUDED.contains_fragrance,
    vat_rate = EXCLUDED.vat_rate,
    price_includes_vat = EXCLUDED.price_includes_vat,
    warnings = EXCLUDED.warnings,
    brand_verification_status = EXCLUDED.brand_verification_status,
    image_ownership_status = EXCLUDED.image_ownership_status,
    ingredient_verification_status = EXCLUDED.ingredient_verification_status,
    claims_validation_status = EXCLUDED.claims_validation_status,
    images_validation_status = EXCLUDED.images_validation_status,
    stock_validation_status = EXCLUDED.stock_validation_status,
    certifications_validation_status = EXCLUDED.certifications_validation_status,
    translations_validation_status = EXCLUDED.translations_validation_status,
    minor_safety_status = EXCLUDED.minor_safety_status,
    image_supervision_status = EXCLUDED.image_supervision_status;

INSERT INTO public.products (
    id, slug, name, brand, price, category, subcategory, description, image_url, inci, ingredients, skin_types, concerns, country_availability, is_active, catalog_status, is_preorder, badges, stock_quantity, in_stock, source_supplier, supplier_id, routine_step, size_label, texture, usage_frequency, benefit_primary, for_who, not_ideal_if, how_to_use, fragrance, contains_fragrance, vat_rate, price_includes_vat, warnings, brand_verification_status, image_ownership_status, ingredient_verification_status, claims_validation_status, images_validation_status, stock_validation_status, certifications_validation_status, translations_validation_status, minor_safety_status, image_supervision_status
  ) VALUES (
    'peau-ess-011',
    'gel-acide-hyaluronique-30ml',
    'Gel Acide Hyaluronique — 30ml',
    'KURLA Skincare',
    14.90,
    'peau',
    'Hydratation',
    '[PRÉCOMMANDE — expédié sous 30 jours maximum] Acide hyaluronique de deux poids moléculaires : le haut poids moléculaire retient l’eau en surface, le bas poids moléculaire pénètre davantage. Sans corps gras, ce qui en fait l’hydratant des peaux à imperfections qui ne supportent pas les crèmes riches.',
    'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?auto=format&fit=crop&w=800&q=80',
    'Aqua, Sodium Hyaluronate, Glycerin, Panthenol, Betaine, Allantoin, Xanthan Gum, Phenoxyethanol',
    ARRAY['Acide Hyaluronique', 'Glycérine Végétale', 'Panthénol', 'Allantoïne']::TEXT[],
    ARRAY['mixte', 'grasse', 'sensible', 'seche']::TEXT[],
    ARRAY['hydrater_peau', 'barriere_cutanee', 'imperfections_acne']::TEXT[],
    ARRAY['FR', 'BE', 'DOM', 'INT']::TEXT[],
    TRUE,
    'published',
    TRUE,
    ARRAY['preorder', 'sans-parfum']::TEXT[],
    0,
    TRUE,
    'KURLA Skincare — formulation interne (précommande)',
    'sup-brands-wholesale',
    'Gel hydratant',
    '30ml',
    'Gel frais, fini non gras, sans effet collant',
    'Matin et soir',
    'Hydrate sans graisser ni charger les pores',
    'Peaux mixtes à grasses, déshydratées, à imperfections, ou toute peau en climat chaud et humide.',
    'Peau très sèche en hiver : insuffisant seul, à associer à la crème céramides.',
    '2 à 3 pressions sur peau humide — l’acide hyaluronique a besoin d’eau pour fonctionner, sinon il assèche. Refermer aussitôt avec la crème.',
    'Sans parfum ajouté',
    FALSE,
    20.00,
    TRUE,
    ARRAY['Toujours appliquer sur peau humide et refermer avec une crème : seul sur peau sèche, un gel d’acide hyaluronique peut accentuer la déshydratation.']::TEXT[],
    'verified',
    'illustrative',
    'pending',
    'pending',
    'pending',
    'pending',
    'pending',
    'pending',
    'not_provided',
    'not_provided'
  )
  ON CONFLICT (id) DO UPDATE SET
    slug = EXCLUDED.slug,
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    price = EXCLUDED.price,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    description = EXCLUDED.description,
    image_url = EXCLUDED.image_url,
    inci = EXCLUDED.inci,
    ingredients = EXCLUDED.ingredients,
    skin_types = EXCLUDED.skin_types,
    concerns = EXCLUDED.concerns,
    country_availability = EXCLUDED.country_availability,
    is_active = EXCLUDED.is_active,
    catalog_status = EXCLUDED.catalog_status,
    is_preorder = EXCLUDED.is_preorder,
    badges = EXCLUDED.badges,
    stock_quantity = EXCLUDED.stock_quantity,
    in_stock = EXCLUDED.in_stock,
    source_supplier = EXCLUDED.source_supplier,
    supplier_id = EXCLUDED.supplier_id,
    routine_step = EXCLUDED.routine_step,
    size_label = EXCLUDED.size_label,
    texture = EXCLUDED.texture,
    usage_frequency = EXCLUDED.usage_frequency,
    benefit_primary = EXCLUDED.benefit_primary,
    for_who = EXCLUDED.for_who,
    not_ideal_if = EXCLUDED.not_ideal_if,
    how_to_use = EXCLUDED.how_to_use,
    fragrance = EXCLUDED.fragrance,
    contains_fragrance = EXCLUDED.contains_fragrance,
    vat_rate = EXCLUDED.vat_rate,
    price_includes_vat = EXCLUDED.price_includes_vat,
    warnings = EXCLUDED.warnings,
    brand_verification_status = EXCLUDED.brand_verification_status,
    image_ownership_status = EXCLUDED.image_ownership_status,
    ingredient_verification_status = EXCLUDED.ingredient_verification_status,
    claims_validation_status = EXCLUDED.claims_validation_status,
    images_validation_status = EXCLUDED.images_validation_status,
    stock_validation_status = EXCLUDED.stock_validation_status,
    certifications_validation_status = EXCLUDED.certifications_validation_status,
    translations_validation_status = EXCLUDED.translations_validation_status,
    minor_safety_status = EXCLUDED.minor_safety_status,
    image_supervision_status = EXCLUDED.image_supervision_status;

INSERT INTO public.products (
    id, slug, name, brand, price, category, subcategory, description, image_url, inci, ingredients, skin_types, concerns, country_availability, is_active, catalog_status, is_preorder, badges, stock_quantity, in_stock, source_supplier, supplier_id, routine_step, size_label, texture, usage_frequency, benefit_primary, for_who, not_ideal_if, how_to_use, fragrance, contains_fragrance, vat_rate, price_includes_vat, warnings, brand_verification_status, image_ownership_status, ingredient_verification_status, claims_validation_status, images_validation_status, stock_validation_status, certifications_validation_status, translations_validation_status, minor_safety_status, image_supervision_status
  ) VALUES (
    'peau-ess-012',
    'creme-riche-ceramides-peaux-tres-seches-50ml',
    'Crème Riche Céramides Peaux Très Sèches — 50ml',
    'KURLA Skincare',
    19.90,
    'peau',
    'Hydratation',
    '[PRÉCOMMANDE — expédié sous 30 jours maximum] Trois céramides, cholestérol et squalane dans les proportions du ciment lipidique cutané, plus du beurre de karité pour l’occlusion. Sans parfum, parce qu’une peau qui tiraille est une peau dont la barrière est perméable — et donc réactive au parfum.',
    'https://images.unsplash.com/photo-1570554886111-eafa33934098?auto=format&fit=crop&w=800&q=80',
    'Aqua, Glycerin, Caprylic/Capric Triglyceride, Ceramide NP, Ceramide AP, Cholesterol, Squalane, Butyrospermum Parkii Butter, Panthenol, Tocopherol, Phenoxyethanol',
    ARRAY['Céramides NP & AP', 'Cholestérol', 'Beurre de Karité', 'Squalane Végétal']::TEXT[],
    ARRAY['seche', 'tres_seche', 'sensible']::TEXT[],
    ARRAY['hydrater_peau', 'barriere_cutanee', 'peau_sensible']::TEXT[],
    ARRAY['FR', 'BE', 'DOM', 'INT']::TEXT[],
    TRUE,
    'published',
    TRUE,
    ARRAY['preorder', 'sans-parfum']::TEXT[],
    0,
    TRUE,
    'KURLA Skincare — formulation interne (précommande)',
    'sup-brands-wholesale',
    'Hydratant céramides',
    '50ml',
    'Baume fondant, fini nourrissant sans film gras',
    'Matin et soir',
    'Restaure la barrière et stoppe les tiraillements',
    'Peaux très sèches à atopiques, tiraillements, desquamation, peaux matures, climats froids et secs.',
    'Peaux grasses à imperfections : préférer le gel acide hyaluronique.',
    'Une noisette matin et soir, sur peau légèrement humide. Peut s’appliquer en couche épaisse le soir en cas de tiraillements marqués.',
    'Sans parfum ajouté',
    FALSE,
    20.00,
    TRUE,
    ARRAY[]::TEXT[],
    'verified',
    'illustrative',
    'pending',
    'pending',
    'pending',
    'pending',
    'pending',
    'pending',
    'not_provided',
    'not_provided'
  )
  ON CONFLICT (id) DO UPDATE SET
    slug = EXCLUDED.slug,
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    price = EXCLUDED.price,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    description = EXCLUDED.description,
    image_url = EXCLUDED.image_url,
    inci = EXCLUDED.inci,
    ingredients = EXCLUDED.ingredients,
    skin_types = EXCLUDED.skin_types,
    concerns = EXCLUDED.concerns,
    country_availability = EXCLUDED.country_availability,
    is_active = EXCLUDED.is_active,
    catalog_status = EXCLUDED.catalog_status,
    is_preorder = EXCLUDED.is_preorder,
    badges = EXCLUDED.badges,
    stock_quantity = EXCLUDED.stock_quantity,
    in_stock = EXCLUDED.in_stock,
    source_supplier = EXCLUDED.source_supplier,
    supplier_id = EXCLUDED.supplier_id,
    routine_step = EXCLUDED.routine_step,
    size_label = EXCLUDED.size_label,
    texture = EXCLUDED.texture,
    usage_frequency = EXCLUDED.usage_frequency,
    benefit_primary = EXCLUDED.benefit_primary,
    for_who = EXCLUDED.for_who,
    not_ideal_if = EXCLUDED.not_ideal_if,
    how_to_use = EXCLUDED.how_to_use,
    fragrance = EXCLUDED.fragrance,
    contains_fragrance = EXCLUDED.contains_fragrance,
    vat_rate = EXCLUDED.vat_rate,
    price_includes_vat = EXCLUDED.price_includes_vat,
    warnings = EXCLUDED.warnings,
    brand_verification_status = EXCLUDED.brand_verification_status,
    image_ownership_status = EXCLUDED.image_ownership_status,
    ingredient_verification_status = EXCLUDED.ingredient_verification_status,
    claims_validation_status = EXCLUDED.claims_validation_status,
    images_validation_status = EXCLUDED.images_validation_status,
    stock_validation_status = EXCLUDED.stock_validation_status,
    certifications_validation_status = EXCLUDED.certifications_validation_status,
    translations_validation_status = EXCLUDED.translations_validation_status,
    minor_safety_status = EXCLUDED.minor_safety_status,
    image_supervision_status = EXCLUDED.image_supervision_status;

INSERT INTO public.products (
    id, slug, name, brand, price, category, subcategory, description, image_url, inci, ingredients, skin_types, concerns, country_availability, is_active, catalog_status, is_preorder, badges, stock_quantity, in_stock, source_supplier, supplier_id, routine_step, size_label, texture, usage_frequency, benefit_primary, for_who, not_ideal_if, how_to_use, fragrance, contains_fragrance, vat_rate, price_includes_vat, warnings, brand_verification_status, image_ownership_status, ingredient_verification_status, claims_validation_status, images_validation_status, stock_validation_status, certifications_validation_status, translations_validation_status, minor_safety_status, image_supervision_status
  ) VALUES (
    'peau-ess-013',
    'baume-levres-ceramides-10ml',
    'Baume Lèvres Céramides — 10ml',
    'KURLA Skincare',
    8.90,
    'peau',
    'Hydratation',
    '[PRÉCOMMANDE — expédié sous 30 jours maximum] Les lèvres n’ont pas de glandes sébacées : elles ne se réparent pas seules. Céramides et squalane pour le ciment lipidique, cire d’abeille pour l’occlusion, ricin pour le glissant. Sans menthol ni camphre, deux irritants courants qui entretiennent le cycle « je mets du baume, je remets du baume ».',
    'https://images.unsplash.com/photo-1507152832244-10d45c7eda57?auto=format&fit=crop&w=800&q=80',
    'Ricinus Communis Seed Oil, Butyrospermum Parkii Butter, Cera Alba, Ceramide NP, Squalane, Tocopherol',
    ARRAY['Céramides NP', 'Cire d’Abeille', 'Beurre de Karité', 'Squalane Végétal']::TEXT[],
    ARRAY['seche', 'tres_seche', 'sensible']::TEXT[],
    ARRAY['barriere_cutanee', 'hydrater_peau']::TEXT[],
    ARRAY['FR', 'BE', 'DOM', 'INT']::TEXT[],
    TRUE,
    'published',
    TRUE,
    ARRAY['preorder', 'sans-parfum']::TEXT[],
    0,
    TRUE,
    'KURLA Skincare — formulation interne (précommande)',
    'sup-brands-wholesale',
    'Baume lèvres',
    '10ml',
    'Baume onctueux, fini satiné non collant',
    'Aussi souvent que nécessaire',
    'Répare les lèvres gercées durablement',
    'Lèvres gercées, sèches, ou asséchées par un traitement (rétinol, isotrétinoïne).',
    'Aucune contre-indication.',
    'Appliquer au besoin, en couche épaisse le soir. Aussi en contour des lèvres.',
    'Sans parfum ajouté',
    FALSE,
    20.00,
    TRUE,
    ARRAY[]::TEXT[],
    'verified',
    'illustrative',
    'pending',
    'pending',
    'pending',
    'pending',
    'pending',
    'pending',
    'not_provided',
    'not_provided'
  )
  ON CONFLICT (id) DO UPDATE SET
    slug = EXCLUDED.slug,
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    price = EXCLUDED.price,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    description = EXCLUDED.description,
    image_url = EXCLUDED.image_url,
    inci = EXCLUDED.inci,
    ingredients = EXCLUDED.ingredients,
    skin_types = EXCLUDED.skin_types,
    concerns = EXCLUDED.concerns,
    country_availability = EXCLUDED.country_availability,
    is_active = EXCLUDED.is_active,
    catalog_status = EXCLUDED.catalog_status,
    is_preorder = EXCLUDED.is_preorder,
    badges = EXCLUDED.badges,
    stock_quantity = EXCLUDED.stock_quantity,
    in_stock = EXCLUDED.in_stock,
    source_supplier = EXCLUDED.source_supplier,
    supplier_id = EXCLUDED.supplier_id,
    routine_step = EXCLUDED.routine_step,
    size_label = EXCLUDED.size_label,
    texture = EXCLUDED.texture,
    usage_frequency = EXCLUDED.usage_frequency,
    benefit_primary = EXCLUDED.benefit_primary,
    for_who = EXCLUDED.for_who,
    not_ideal_if = EXCLUDED.not_ideal_if,
    how_to_use = EXCLUDED.how_to_use,
    fragrance = EXCLUDED.fragrance,
    contains_fragrance = EXCLUDED.contains_fragrance,
    vat_rate = EXCLUDED.vat_rate,
    price_includes_vat = EXCLUDED.price_includes_vat,
    warnings = EXCLUDED.warnings,
    brand_verification_status = EXCLUDED.brand_verification_status,
    image_ownership_status = EXCLUDED.image_ownership_status,
    ingredient_verification_status = EXCLUDED.ingredient_verification_status,
    claims_validation_status = EXCLUDED.claims_validation_status,
    images_validation_status = EXCLUDED.images_validation_status,
    stock_validation_status = EXCLUDED.stock_validation_status,
    certifications_validation_status = EXCLUDED.certifications_validation_status,
    translations_validation_status = EXCLUDED.translations_validation_status,
    minor_safety_status = EXCLUDED.minor_safety_status,
    image_supervision_status = EXCLUDED.image_supervision_status;

INSERT INTO public.products (
    id, slug, name, brand, price, category, subcategory, description, image_url, inci, ingredients, skin_types, concerns, country_availability, is_active, catalog_status, is_preorder, badges, stock_quantity, in_stock, source_supplier, supplier_id, routine_step, size_label, texture, usage_frequency, benefit_primary, for_who, not_ideal_if, how_to_use, fragrance, contains_fragrance, vat_rate, price_includes_vat, warnings, brand_verification_status, image_ownership_status, ingredient_verification_status, claims_validation_status, images_validation_status, stock_validation_status, certifications_validation_status, translations_validation_status, minor_safety_status, image_supervision_status
  ) VALUES (
    'peau-ess-014',
    'spf-50-invisible-teinte-40ml',
    'SPF 50+ Invisible Teinté — 40ml',
    'KURLA Skincare',
    22.90,
    'peau',
    'Protection Solaire',
    '[PRÉCOMMANDE — expédié sous 30 jours maximum] Filtres organiques de nouvelle génération, sans filtre minéral en surface : c’est le trio avobenzone/oxyde de zinc qui produit le voile gris sur les peaux foncées, et il est absent ici. Les oxydes de fer apportent la teinte et protègent aussi contre la lumière visible — celle qui entretient les taches sur les peaux riches en mélanine, et que les SPF classiques ne filtrent pas.',
    'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=800&q=80',
    'Aqua, Ethylhexyl Triazone, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, Diethylamino Hydroxybenzoyl Hexyl Benzoate, Glycerin, Iron Oxides (CI 77491, CI 77492, CI 77499), Squalane, Tocopherol, Phenoxyethanol',
    ARRAY['Filtres UVA/UVB Nouvelle Génération', 'Oxydes de Fer', 'Squalane Végétal', 'Vitamine E']::TEXT[],
    ARRAY['mixte', 'grasse', 'seche', 'sensible', 'foncee']::TEXT[],
    ARRAY['protection_solaire', 'taches_hyperpigmentation']::TEXT[],
    ARRAY['FR', 'BE', 'DOM', 'INT']::TEXT[],
    TRUE,
    'published',
    TRUE,
    ARRAY['preorder', 'sans-parfum', 'invisible']::TEXT[],
    0,
    TRUE,
    'KURLA Skincare — formulation interne (précommande)',
    'sup-brands-wholesale',
    'SPF 50+ invisible',
    '40ml',
    'Fluide teinté, fini naturel sans trace blanche',
    'Chaque matin, toute l’année',
    'Protège sans trace blanche sur les peaux foncées',
    'Peaux moyennes à foncées, taches en cours de traitement, exposition quotidienne urbaine.',
    'Peaux très claires : la teinte unique peut être trop soutenue.',
    'Deux doigts de produit en dernière étape de la routine du matin, avant le maquillage. Renouveler toutes les 2 heures en cas d’exposition directe.',
    'Sans parfum ajouté',
    FALSE,
    20.00,
    TRUE,
    ARRAY['Aucun produit solaire ne protège à 100 %. Renouveler l’application toutes les 2 heures en exposition directe. Une tache qui évolue relève d’un avis médical.']::TEXT[],
    'verified',
    'illustrative',
    'pending',
    'pending',
    'pending',
    'pending',
    'pending',
    'pending',
    'not_provided',
    'not_provided'
  )
  ON CONFLICT (id) DO UPDATE SET
    slug = EXCLUDED.slug,
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    price = EXCLUDED.price,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    description = EXCLUDED.description,
    image_url = EXCLUDED.image_url,
    inci = EXCLUDED.inci,
    ingredients = EXCLUDED.ingredients,
    skin_types = EXCLUDED.skin_types,
    concerns = EXCLUDED.concerns,
    country_availability = EXCLUDED.country_availability,
    is_active = EXCLUDED.is_active,
    catalog_status = EXCLUDED.catalog_status,
    is_preorder = EXCLUDED.is_preorder,
    badges = EXCLUDED.badges,
    stock_quantity = EXCLUDED.stock_quantity,
    in_stock = EXCLUDED.in_stock,
    source_supplier = EXCLUDED.source_supplier,
    supplier_id = EXCLUDED.supplier_id,
    routine_step = EXCLUDED.routine_step,
    size_label = EXCLUDED.size_label,
    texture = EXCLUDED.texture,
    usage_frequency = EXCLUDED.usage_frequency,
    benefit_primary = EXCLUDED.benefit_primary,
    for_who = EXCLUDED.for_who,
    not_ideal_if = EXCLUDED.not_ideal_if,
    how_to_use = EXCLUDED.how_to_use,
    fragrance = EXCLUDED.fragrance,
    contains_fragrance = EXCLUDED.contains_fragrance,
    vat_rate = EXCLUDED.vat_rate,
    price_includes_vat = EXCLUDED.price_includes_vat,
    warnings = EXCLUDED.warnings,
    brand_verification_status = EXCLUDED.brand_verification_status,
    image_ownership_status = EXCLUDED.image_ownership_status,
    ingredient_verification_status = EXCLUDED.ingredient_verification_status,
    claims_validation_status = EXCLUDED.claims_validation_status,
    images_validation_status = EXCLUDED.images_validation_status,
    stock_validation_status = EXCLUDED.stock_validation_status,
    certifications_validation_status = EXCLUDED.certifications_validation_status,
    translations_validation_status = EXCLUDED.translations_validation_status,
    minor_safety_status = EXCLUDED.minor_safety_status,
    image_supervision_status = EXCLUDED.image_supervision_status;

INSERT INTO public.products (
    id, slug, name, brand, price, category, subcategory, description, image_url, inci, ingredients, skin_types, concerns, country_availability, is_active, catalog_status, is_preorder, badges, stock_quantity, in_stock, source_supplier, supplier_id, routine_step, size_label, texture, usage_frequency, benefit_primary, for_who, not_ideal_if, how_to_use, fragrance, contains_fragrance, vat_rate, price_includes_vat, warnings, brand_verification_status, image_ownership_status, ingredient_verification_status, claims_validation_status, images_validation_status, stock_validation_status, certifications_validation_status, translations_validation_status, minor_safety_status, image_supervision_status
  ) VALUES (
    'peau-ess-015',
    'soin-local-imperfections-bha-2-zinc-15ml',
    'Soin Local Imperfections BHA 2% + Zinc — 15ml',
    'KURLA Skincare',
    12.90,
    'peau',
    'Traitement',
    '[PRÉCOMMANDE — expédié sous 30 jours maximum] Acide salicylique à 2 % et zinc en application localisée, pour ne pas exfolier le reste du visage. Le geste compte autant que la formule : un soin local s’applique sur le bouton, pas sur la joue, et un bouton qu’on perce laisse une marque qui met des mois à s’estomper — c’est le mécanisme principal des taches post-inflammatoires.',
    'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?auto=format&fit=crop&w=800&q=80',
    'Aqua, Salicylic Acid, Zinc PCA, Niacinamide, Glycerin, Panthenol, Allantoin, Xanthan Gum, Phenoxyethanol',
    ARRAY['Acide Salicylique 2%', 'Zinc PCA', 'Niacinamide', 'Allantoïne']::TEXT[],
    ARRAY['mixte', 'grasse']::TEXT[],
    ARRAY['imperfections_acne']::TEXT[],
    ARRAY['FR', 'BE', 'DOM', 'INT']::TEXT[],
    TRUE,
    'published',
    TRUE,
    ARRAY['preorder', 'sans-parfum']::TEXT[],
    0,
    TRUE,
    'KURLA Skincare — formulation interne (précommande)',
    'sup-brands-wholesale',
    'Soin local',
    '15ml',
    'Gel transparent, séchage rapide',
    'Le soir, sur le bouton uniquement',
    'Assèche le bouton sans agresser la zone autour',
    'Imperfections localisées, pores obstrués, poussées ponctuelles.',
    'Peau irritée autour de la zone, grossesse (acide salicylique), usage sur une grande surface.',
    'Une touche le soir, sur le bouton propre et sec. Ne pas étaler sur l’ensemble du visage. Laisser sécher.',
    'Sans parfum ajouté',
    FALSE,
    20.00,
    TRUE,
    ARRAY['Usage localisé uniquement. Ne pas percer ni triturer : la marque laissée met plusieurs mois à s’estomper, contre quelques jours pour le bouton.']::TEXT[],
    'verified',
    'illustrative',
    'pending',
    'pending',
    'pending',
    'pending',
    'pending',
    'pending',
    'not_provided',
    'not_provided'
  )
  ON CONFLICT (id) DO UPDATE SET
    slug = EXCLUDED.slug,
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    price = EXCLUDED.price,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    description = EXCLUDED.description,
    image_url = EXCLUDED.image_url,
    inci = EXCLUDED.inci,
    ingredients = EXCLUDED.ingredients,
    skin_types = EXCLUDED.skin_types,
    concerns = EXCLUDED.concerns,
    country_availability = EXCLUDED.country_availability,
    is_active = EXCLUDED.is_active,
    catalog_status = EXCLUDED.catalog_status,
    is_preorder = EXCLUDED.is_preorder,
    badges = EXCLUDED.badges,
    stock_quantity = EXCLUDED.stock_quantity,
    in_stock = EXCLUDED.in_stock,
    source_supplier = EXCLUDED.source_supplier,
    supplier_id = EXCLUDED.supplier_id,
    routine_step = EXCLUDED.routine_step,
    size_label = EXCLUDED.size_label,
    texture = EXCLUDED.texture,
    usage_frequency = EXCLUDED.usage_frequency,
    benefit_primary = EXCLUDED.benefit_primary,
    for_who = EXCLUDED.for_who,
    not_ideal_if = EXCLUDED.not_ideal_if,
    how_to_use = EXCLUDED.how_to_use,
    fragrance = EXCLUDED.fragrance,
    contains_fragrance = EXCLUDED.contains_fragrance,
    vat_rate = EXCLUDED.vat_rate,
    price_includes_vat = EXCLUDED.price_includes_vat,
    warnings = EXCLUDED.warnings,
    brand_verification_status = EXCLUDED.brand_verification_status,
    image_ownership_status = EXCLUDED.image_ownership_status,
    ingredient_verification_status = EXCLUDED.ingredient_verification_status,
    claims_validation_status = EXCLUDED.claims_validation_status,
    images_validation_status = EXCLUDED.images_validation_status,
    stock_validation_status = EXCLUDED.stock_validation_status,
    certifications_validation_status = EXCLUDED.certifications_validation_status,
    translations_validation_status = EXCLUDED.translations_validation_status,
    minor_safety_status = EXCLUDED.minor_safety_status,
    image_supervision_status = EXCLUDED.image_supervision_status;

INSERT INTO public.products (
    id, slug, name, brand, price, category, subcategory, description, image_url, inci, ingredients, skin_types, concerns, country_availability, is_active, catalog_status, is_preorder, badges, stock_quantity, in_stock, source_supplier, supplier_id, routine_step, size_label, texture, usage_frequency, benefit_primary, for_who, not_ideal_if, how_to_use, fragrance, contains_fragrance, vat_rate, price_includes_vat, warnings, brand_verification_status, image_ownership_status, ingredient_verification_status, claims_validation_status, images_validation_status, stock_validation_status, certifications_validation_status, translations_validation_status, minor_safety_status, image_supervision_status
  ) VALUES (
    'peau-ess-016',
    'masque-apaisant-barriere-50ml',
    'Masque Apaisant Barrière — 50ml',
    'KURLA Skincare',
    18.90,
    'peau',
    'Masques',
    '[PRÉCOMMANDE — expédié sous 30 jours maximum] Centella, bisabolol et panthénol pour l’apaisement immédiat, céramides pour la reconstruction lipidique. Pensé pour les soirs où la peau tiraille après un actif un peu trop enthousiaste — c’est le produit de rattrapage de la gamme, pas un soin d’entretien.',
    'https://images.unsplash.com/photo-1526947425960-945c6e72858f?auto=format&fit=crop&w=800&q=80',
    'Aqua, Glycerin, Squalane, Ceramide NP, Panthenol, Allantoin, Bisabolol, Centella Asiatica Extract, Butyrospermum Parkii Butter, Phenoxyethanol',
    ARRAY['Centella Asiatica', 'Céramides NP', 'Bisabolol', 'Panthénol']::TEXT[],
    ARRAY['seche', 'sensible', 'mixte']::TEXT[],
    ARRAY['peau_sensible', 'barriere_cutanee', 'hydrater_peau']::TEXT[],
    ARRAY['FR', 'BE', 'DOM', 'INT']::TEXT[],
    TRUE,
    'published',
    TRUE,
    ARRAY['preorder', 'sans-parfum']::TEXT[],
    0,
    TRUE,
    'KURLA Skincare — formulation interne (précommande)',
    'sup-brands-wholesale',
    'Masque apaisant',
    '50ml',
    'Crème épaisse, rinçage facile',
    '1 à 2 fois par semaine',
    'Calme les irritations et recharge la barrière',
    'Peaux sensibles, réactives, irritées par les actifs (rétinol, acides) ou par le climat.',
    'Aucune contre-indication ; sans effet sur les imperfections actives.',
    'Couche moyenne sur peau propre, 10 minutes, rincer à l’eau tiède. Peut s’utiliser en couche fine laissée toute la nuit sur les zones irritées.',
    'Sans parfum ajouté',
    FALSE,
    20.00,
    TRUE,
    ARRAY[]::TEXT[],
    'verified',
    'illustrative',
    'pending',
    'pending',
    'pending',
    'pending',
    'pending',
    'pending',
    'not_provided',
    'not_provided'
  )
  ON CONFLICT (id) DO UPDATE SET
    slug = EXCLUDED.slug,
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    price = EXCLUDED.price,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    description = EXCLUDED.description,
    image_url = EXCLUDED.image_url,
    inci = EXCLUDED.inci,
    ingredients = EXCLUDED.ingredients,
    skin_types = EXCLUDED.skin_types,
    concerns = EXCLUDED.concerns,
    country_availability = EXCLUDED.country_availability,
    is_active = EXCLUDED.is_active,
    catalog_status = EXCLUDED.catalog_status,
    is_preorder = EXCLUDED.is_preorder,
    badges = EXCLUDED.badges,
    stock_quantity = EXCLUDED.stock_quantity,
    in_stock = EXCLUDED.in_stock,
    source_supplier = EXCLUDED.source_supplier,
    supplier_id = EXCLUDED.supplier_id,
    routine_step = EXCLUDED.routine_step,
    size_label = EXCLUDED.size_label,
    texture = EXCLUDED.texture,
    usage_frequency = EXCLUDED.usage_frequency,
    benefit_primary = EXCLUDED.benefit_primary,
    for_who = EXCLUDED.for_who,
    not_ideal_if = EXCLUDED.not_ideal_if,
    how_to_use = EXCLUDED.how_to_use,
    fragrance = EXCLUDED.fragrance,
    contains_fragrance = EXCLUDED.contains_fragrance,
    vat_rate = EXCLUDED.vat_rate,
    price_includes_vat = EXCLUDED.price_includes_vat,
    warnings = EXCLUDED.warnings,
    brand_verification_status = EXCLUDED.brand_verification_status,
    image_ownership_status = EXCLUDED.image_ownership_status,
    ingredient_verification_status = EXCLUDED.ingredient_verification_status,
    claims_validation_status = EXCLUDED.claims_validation_status,
    images_validation_status = EXCLUDED.images_validation_status,
    stock_validation_status = EXCLUDED.stock_validation_status,
    certifications_validation_status = EXCLUDED.certifications_validation_status,
    translations_validation_status = EXCLUDED.translations_validation_status,
    minor_safety_status = EXCLUDED.minor_safety_status,
    image_supervision_status = EXCLUDED.image_supervision_status;

-- Cohérence : les trois fiches déjà publiées portaient la précommande
-- uniquement dans badges[], faute de colonne. La colonne existe depuis
-- 20260901000000, on aligne.
UPDATE public.products
   SET is_preorder = TRUE
 WHERE id IN ('peau-ess-001', 'peau-ess-002', 'peau-ess-003')
   AND is_preorder IS DISTINCT FROM TRUE;
