-- ============================================================
-- KURLA BEAUTY - OPERATIONS INTEGRITY
-- UUID compatibility, shipment uniqueness and notification contracts.
-- ============================================================

-- 1. Keep one current shipment per order before enabling upsert(order_id).
DO $$
DECLARE
  duplicate RECORD;
  keeper UUID;
  old_shipment UUID;
BEGIN
  FOR duplicate IN
    SELECT order_id, array_agg(id ORDER BY updated_at DESC NULLS LAST, created_at DESC NULLS LAST, id) AS shipment_ids
    FROM public.shipments
    GROUP BY order_id
    HAVING COUNT(*) > 1
  LOOP
    keeper := duplicate.shipment_ids[1];
    FOREACH old_shipment IN ARRAY duplicate.shipment_ids[2:array_length(duplicate.shipment_ids, 1)]
    LOOP
      UPDATE public.shipping_events SET shipment_id = keeper WHERE shipment_id = old_shipment;
      DELETE FROM public.shipments WHERE id = old_shipment;
    END LOOP;
  END LOOP;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS idx_shipments_order_id_unique
  ON public.shipments(order_id);

ALTER TABLE public.shipments DROP CONSTRAINT IF EXISTS shipments_status_check;
ALTER TABLE public.shipments
  ADD CONSTRAINT shipments_status_check CHECK (
    status IN ('preparing', 'label_created', 'shipped', 'in_transit', 'out_for_delivery', 'delivered', 'failed')
  );

-- 2. IDs generated by the service are UUIDs, matching all operational tables.
-- Expand the notification contract to cover every status-derived notification
-- emitted by serverDb, including the legacy local-test names.
ALTER TABLE public.notifications DROP CONSTRAINT IF EXISTS notifications_type_check;
ALTER TABLE public.notifications
  ADD CONSTRAINT notifications_type_check CHECK (
    type IN (
      'account_created',
      'email_confirmation_pending',
      'payment_pending',
      'payment_confirmed',
      'payment_failed',
      'order_pending_payment',
      'order_payment_pending_webhook',
      'order_paid',
      'order_created',
      'order_received',
      'order_payment_failed',
      'order_processing',
      'order_packed',
      'order_shipped',
      'order_delivered',
      'order_cancelled',
      'order_refunded',
      'order_partially_refunded',
      'order_return_requested',
      'order_returned',
      'refund_created',
      'return_requested',
      'support_reply',
      'low_stock',
      'routine_reminder'
    )
  );

-- 3. Validate that historical operational identifiers are compatible with the
-- UUID columns used by the service. The application now generates UUIDs for
-- all new records; malformed legacy rows require manual remediation rather
-- than an implicit destructive cast.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM public.notifications WHERE id IS NULL)
     OR EXISTS (SELECT 1 FROM public.returns WHERE id IS NULL)
     OR EXISTS (SELECT 1 FROM public.support_tickets WHERE id IS NULL)
     OR EXISTS (SELECT 1 FROM public.support_messages WHERE id IS NULL) THEN
    RAISE EXCEPTION 'KURLA operations integrity failed: null operational identifier';
  END IF;
END $$;
