-- ============================================================
-- KURLA BEAUTY - DEMO PRODUCTS SEED MIGRATION (IDEMPOTENT)
-- ============================================================

-- 1. BRANDS SEED
INSERT INTO public.brands (name, description) VALUES
  ('KURLA Botanicals', 'Soins botaniques aux actifs d’origine naturelle pour cheveux texturés'),
  ('KURLA Care', 'Soins ciblés cuir chevelu et coiffures protectrices (Braids, Twists, Locks)'),
  ('KURLA Skincare', 'Soins dermo-cosmétiques formulés pour les peaux mélaninées'),
  ('KURLA Essentials', 'Accessoires et outils de protection capillaire de haute qualité'),
  ('KURLA Kids', 'Gammes hypoallergéniques et ultra douces sans larmes pour enfants'),
  ('KURLA Men', 'Soins barbe, rasage et cuir chevelu spécial hommes'),
  ('Eadem', 'Soins anti-taches formulés par des chimistes afro-descendantes'),
  ('Black Girl Sunscreen', 'Écrans solaires invisibles formulés pour les peaux riches en mélanine')
ON CONFLICT (name) DO NOTHING;

-- 2. CATEGORIES SEED
INSERT INTO public.categories (slug, name, description) VALUES
  ('cheveux', 'Soins Cheveux', 'Shampoings, masques, leave-in et huiles pour cheveux crépus, bouclés et frisés'),
  ('peau', 'Soins Peau & Teint', 'Sérums, crèmes et protections solaires pour peaux mates et foncées'),
  ('accessoires', 'Accessoires & Protection', 'Bonnets en satin, brosses flex et taies d’oreiller en soie'),
  ('enfants', 'Gammes Enfants', 'Soins démêlants et protecteurs formulés spécialement pour enfants'),
  ('hommes', 'Soins Hommes & Barbe', 'Soins barbe, anti-poils incarnés et grooming')
ON CONFLICT (slug) DO NOTHING;

-- 3. PRODUCTS SEED (SOURCE OF TRUTH IN SUPABASE)
INSERT INTO public.products (
  id, slug, name, brand, category, subcategory, price, in_stock, stock_quantity,
  description, image_url, ingredients, hair_types, skin_types, concerns, country_availability, is_active
) VALUES
(
  'p1',
  'leave-in-hydratant',
  'Leave-In Hydratant Cacao & Mangue (Démo)',
  'KURLA Botanicals',
  'cheveux',
  'Hydratation',
  18.90,
  true,
  100,
  'Une crème riche et fondante qui scelle l’hydratation dans la fibre sans peser. Protège de la casse au démêlage.',
  'https://images.unsplash.com/photo-1608248597261-e4d09123fe1c?auto=format&fit=crop&w=800&q=80',
  ARRAY['Beurre de Mangue', 'Extrait de Cacao', 'Protéine de Soie végétale', 'Huile de Tournesol'],
  ARRAY['4A', '4B', '4C', '3C'],
  ARRAY[]::TEXT[],
  ARRAY['hydrater_cheveux', 'reduire_casse', 'definir_boucles'],
  ARRAY['FR', 'BE', 'DOM', 'AFR', 'INT'],
  true
),
(
  'p2',
  'shampoing-doux',
  'Shampoing Doux Sans Sulfates (Démo)',
  'KURLA Botanicals',
  'cheveux',
  'Lavage',
  14.90,
  true,
  100,
  'Nettoie en douceur le cuir chevelu sans éliminer les huiles naturelles indispensables à la souplesse des boucles.',
  'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=800&q=80',
  ARRAY['Extrait de Guimauve', 'Aloe Vera Pur', 'Cocamidopropyl Betaine'],
  ARRAY['4A', '4B', '4C', '3A', '3B', '3C'],
  ARRAY[]::TEXT[],
  ARRAY['cuir_chevelu', 'hydrater_cheveux', 'demeler_cheveux'],
  ARRAY['FR', 'BE', 'DOM', 'AFR', 'INT'],
  true
),
(
  'p3',
  'masque-hydratant',
  'Masque Hydratant Profond Porosité Forte (Démo)',
  'KURLA Botanicals',
  'cheveux',
  'Soin Réparateur',
  24.90,
  true,
  80,
  'Renforce les ponts de la fibre capillaire texturée pour stopper la casse lors du brossage.',
  'https://images.unsplash.com/photo-1526947425960-945c6e72858f?auto=format&fit=crop&w=800&q=80',
  ARRAY['Huile de Carapate (Black Castor)', 'Acide Hyaluronique capillaire', 'Kératine végétale'],
  ARRAY['4A', '4B', '4C'],
  ARRAY[]::TEXT[],
  ARRAY['reduire_casse', 'hydrater_cheveux'],
  ARRAY['FR', 'BE', 'DOM', 'AFR', 'INT'],
  true
),
(
  'p4',
  'spray-protective-style',
  'Spray Apaisant Braids & Locks Menthe (Démo)',
  'KURLA Care',
  'cheveux',
  'Protective Styles',
  16.90,
  true,
  120,
  'Calme instantanément les tiraillements après la pose de tresses et prévient les pellicules de sécheresse.',
  'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?auto=format&fit=crop&w=800&q=80',
  ARRAY['Hydrolat de Menthe Poivrée', 'Aloe Vera Pur', 'Extrait d’Arbre à Thé', 'Glycérine Végétale'],
  ARRAY['4A', '4B', '4C', 'Locks', 'Braids'],
  ARRAY[]::TEXT[],
  ARRAY['entretenir_tresses', 'entretenir_locks', 'cuir_chevelu'],
  ARRAY['FR', 'BE', 'DOM', 'AFR', 'INT'],
  true
),
(
  'p5',
  'huile-cuir-chevelu',
  'Huile Cuir Chevelu Légère & Pousse (Démo)',
  'KURLA Botanicals',
  'cheveux',
  'Pousse & Densité',
  15.90,
  true,
  90,
  'Formule concentrée en huiles pures pressées à froid pour fortifier la racine et nourrir les longueurs sans alourdir.',
  'https://images.unsplash.com/photo-1608248540480-17637841852d?auto=format&fit=crop&w=800&q=80',
  ARRAY['Huile de Carapate', 'Huile de Romarin à Cinéole', 'Huile de Jojoba', 'Vitamine E'],
  ARRAY['Tous types'],
  ARRAY[]::TEXT[],
  ARRAY['cuir_chevelu', 'reduire_casse', 'entretenir_locks'],
  ARRAY['FR', 'BE', 'DOM', 'AFR', 'INT'],
  true
),
(
  'p6',
  'spf-invisible',
  'Sérum SPF 50+ Invisible Peau Mélaninée (Démo)',
  'KURLA Skincare',
  'peau',
  'Protection Solaire',
  22.90,
  true,
  150,
  'Le premier soin protecteur solaire spécialement formulé pour les carnations riches en mélanine. Protège du photo-vieillissement et évite l’assombrissement des taches.',
  'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=800&q=80',
  ARRAY['Niacinamide 4%', 'Filtres Solaires Organiques invisibles', 'Vitamine E', 'Squalane Végétal'],
  ARRAY[]::TEXT[],
  ARRAY['Peau Mâte', 'Peau Foncée', 'Tous types'],
  ARRAY['protection_solaire', 'taches_hyperpigmentation', 'hydrater_peau'],
  ARRAY['FR', 'BE', 'DOM', 'AFR', 'INT'],
  true
),
(
  'p7',
  'bonnet-satin',
  'Bonnet Satin Microfibre Premium XL (Démo)',
  'KURLA Essentials',
  'accessoires',
  'Nuit & Protection',
  12.90,
  true,
  200,
  'Empêche le coton des oreillers d’absorber l’hydratation naturelle de tes cheveux texturés.',
  'https://images.unsplash.com/photo-1584297091622-af8964893796?auto=format&fit=crop&w=800&q=80',
  ARRAY['Satin de Soie Synthétique Haute Densité Non Absorbant'],
  ARRAY['Tous types'],
  ARRAY[]::TEXT[],
  ARRAY['proteger_nuit', 'entretenir_tresses', 'entretenir_locks', 'reduire_casse'],
  ARRAY['FR', 'BE', 'DOM', 'AFR', 'INT'],
  true
),
(
  'p8',
  'brosse-demelante',
  'Brosse Démêlante Douce Flex-Bristle (Démo)',
  'KURLA Essentials',
  'accessoires',
  'Outils Démêlage',
  9.90,
  true,
  150,
  'Ses picots flexibles épousent les spires des cheveux crépus sans arracher les nœuds.',
  'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80',
  ARRAY['Matériau Ergonomique Souple'],
  ARRAY['4A', '4B', '4C', '3B', '3C'],
  ARRAY[]::TEXT[],
  ARRAY['demeler_cheveux', 'reduire_casse'],
  ARRAY['FR', 'BE', 'DOM', 'AFR', 'INT'],
  true
),
(
  'p9',
  'creme-definition-boucles',
  'Crème Définition Boucles & Twists (Démo)',
  'KURLA Botanicals',
  'cheveux',
  'Coiffage',
  17.90,
  true,
  110,
  'Définit et rebondit les boucles en leur apportant de la brillance sans aucun effet cartonné.',
  'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=800&q=80',
  ARRAY['Beurre de Karité', 'Protéine de Riz', 'Huile d’Argan'],
  ARRAY['3B', '3C', '4A'],
  ARRAY[]::TEXT[],
  ARRAY['definir_boucles', 'hydrater_cheveux'],
  ARRAY['FR', 'BE', 'DOM', 'AFR', 'INT'],
  true
),
(
  'p10',
  'serum-marques-post-imperfections',
  'Sérum Marques Post-Imperfections Niacinamide (Démo)',
  'KURLA Skincare',
  'peau',
  'Éclat & Uniformité',
  29.90,
  true,
  75,
  'Accompagne l’atténuation des marques sombres en douceur sans agresser le film cutané.',
  'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80',
  ARRAY['Niacinamide 5%', 'Acide Tranexamique 3%', 'Zinc PCA'],
  ARRAY[]::TEXT[],
  ARRAY['Mâte', 'Foncée', 'Mixte'],
  ARRAY['taches_hyperpigmentation', 'imperfections_acne', 'peau_sensible'],
  ARRAY['FR', 'BE', 'DOM', 'AFR', 'INT'],
  true
),
(
  'p11',
  'kit-kids-douceur',
  'Kit Complet Kids Douceur & Démêlage (Démo)',
  'KURLA Kids',
  'enfants',
  'Kit Complet',
  49.00,
  true,
  60,
  'Contient le Spray Démêlant, le Leave-in Douceur et la Brosse Flex pour des routines sans larmes.',
  'https://images.unsplash.com/photo-1517677208171-0bc6725a3e60?auto=format&fit=crop&w=800&q=80',
  ARRAY['Aloe Vera Bio', 'Avoine Douce', 'Huile de Caméline'],
  ARRAY['Enfants 3-12 ans'],
  ARRAY[]::TEXT[],
  ARRAY['demeler_cheveux', 'hydrater_cheveux', 'reduire_casse'],
  ARRAY['FR', 'BE', 'DOM', 'AFR', 'INT'],
  true
),
(
  'p12',
  'kit-protective-style',
  'Kit Protective Style Braids & Locks (Démo)',
  'KURLA Care',
  'cheveux',
  'Kit Complete Protective',
  52.00,
  true,
  80,
  'Le trio indispensable : Spray Apaisant Menthe + Huile Cuir Chevelu + Bonnet Satin XL.',
  'https://images.unsplash.com/photo-1589156280159-27698a70f29e?auto=format&fit=crop&w=800&q=80',
  ARRAY['Menthe Poivrée', 'Carapate', 'Satin Grade A'],
  ARRAY['Braids', 'Twists', 'Locks'],
  ARRAY[]::TEXT[],
  ARRAY['entretenir_tresses', 'entretenir_locks', 'cuir_chevelu', 'proteger_nuit'],
  ARRAY['FR', 'BE', 'DOM', 'AFR', 'INT'],
  true
),
(
  'p13',
  'baume-apaisant-apres-rasage-barbe',
  'Baume Apaisant Anti-Poils Incarnés Barbe (Démo)',
  'KURLA Men',
  'hommes',
  'Rasage & Barbe',
  19.90,
  true,
  95,
  'Formule dermatologique prévenant la pseudofolliculite de la barbe (boutons de rasage) et adoucissant les poils drus.',
  'https://images.unsplash.com/photo-1507152832244-10d45c7eda57?auto=format&fit=crop&w=800&q=80',
  ARRAY['Acide Salicylique 1.5%', 'Huile d’Arbre à Thé', 'Aloe Vera', 'Allantoïne'],
  ARRAY[]::TEXT[],
  ARRAY['Peau Homme', 'Sensible'],
  ARRAY['poils_incarnes', 'prendre_soin_barbe', 'peau_sensible'],
  ARRAY['FR', 'BE', 'DOM', 'AFR', 'INT'],
  true
),
(
  'p14',
  'eadem-milk-marvel-serum',
  'Milk Marvel Dark Spot Serum (Démo)',
  'Eadem',
  'peau',
  'Éclat & Uniformité',
  62.00,
  true,
  50,
  'Formulé spécifiquement par des chimistes afro-descendantes pour estomper les taches d’hyperpigmentation sans décolorer la peau saine.',
  'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=800&q=80',
  ARRAY['Amber Algae', 'Niacinamide', 'Vitamin C Ester', 'Encapsulated Kojic Acid'],
  ARRAY[]::TEXT[],
  ARRAY['Mélaninée', 'Tous types'],
  ARRAY['taches_hyperpigmentation', 'hydrater_peau'],
  ARRAY['FR', 'BE', 'DOM', 'INT'],
  true
),
(
  'p15',
  'black-girl-sunscreen-spf30',
  'Black Girl Sunscreen Broad Spectrum SPF 30 (Démo)',
  'Black Girl Sunscreen',
  'peau',
  'Protection Solaire',
  24.90,
  true,
  140,
  'La référence internationale culte d’écran solaire transparent conçu par et pour les femmes aux peaux riches en mélanine.',
  'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=800&q=80',
  ARRAY['Huile d’Avocat', 'Huile de Jojoba', 'Jus de Cacao', 'Tournesol'],
  ARRAY[]::TEXT[],
  ARRAY['Peaux Noires', 'Métissées'],
  ARRAY['protection_solaire', 'hydrater_peau', 'taches_hyperpigmentation'],
  ARRAY['FR', 'BE', 'DOM', 'AFR', 'INT'],
  true
),
(
  'p16',
  'taie-oreiller-soie-naturelle',
  'Taie d’Oreiller 100% Soie de Mûrier 22 Momme (Démo)',
  'KURLA Essentials',
  'accessoires',
  'Nuit & Protection',
  34.90,
  true,
  100,
  'Réduit les frictions capillaires à zéro pendant le sommeil et conserve le niveau d’hydratation naturel de la peau et des cheveux.',
  'https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=800&q=80',
  ARRAY['100% Soie de Mûrier Grade 6A'],
  ARRAY['Tous types'],
  ARRAY[]::TEXT[],
  ARRAY['proteger_nuit', 'reduire_casse', 'hydrater_peau', 'entretenir_locks', 'entretenir_perruque'],
  ARRAY['FR', 'BE', 'DOM', 'AFR', 'INT'],
  true
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  price = EXCLUDED.price,
  in_stock = EXCLUDED.in_stock,
  stock_quantity = EXCLUDED.stock_quantity,
  description = EXCLUDED.description,
  image_url = EXCLUDED.image_url,
  ingredients = EXCLUDED.ingredients,
  hair_types = EXCLUDED.hair_types,
  skin_types = EXCLUDED.skin_types,
  concerns = EXCLUDED.concerns,
  country_availability = EXCLUDED.country_availability,
  is_active = EXCLUDED.is_active,
  updated_at = NOW();

-- 4. CLEAN OLD RELATIONS FOR SEEDED DEMO PRODUCTS (ENSURES IDEMPOTENCY)
DELETE FROM public.product_images WHERE product_id IN (
  'p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8', 'p9', 'p10', 'p11', 'p12', 'p13', 'p14', 'p15', 'p16'
);

DELETE FROM public.product_variants WHERE product_id IN (
  'p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8', 'p9', 'p10', 'p11', 'p12', 'p13', 'p14', 'p15', 'p16'
);

DELETE FROM public.inventory WHERE product_id IN (
  'p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8', 'p9', 'p10', 'p11', 'p12', 'p13', 'p14', 'p15', 'p16'
);

-- 5. PRODUCT IMAGES SEED
INSERT INTO public.product_images (product_id, url, alt, position) VALUES
  ('p1', 'https://images.unsplash.com/photo-1608248597261-e4d09123fe1c?auto=format&fit=crop&w=800&q=80', 'Leave-In Hydratant Flacon', 1),
  ('p1', 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80', 'Texture Cacao Mangue', 2),
  ('p2', 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=800&q=80', 'Shampoing Doux Flacon', 1),
  ('p3', 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?auto=format&fit=crop&w=800&q=80', 'Masque Hydratant Pot', 1),
  ('p4', 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?auto=format&fit=crop&w=800&q=80', 'Spray Apaisant Braids', 1),
  ('p5', 'https://images.unsplash.com/photo-1608248540480-17637841852d?auto=format&fit=crop&w=800&q=80', 'Huile Pipette Cuir Chevelu', 1),
  ('p6', 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=800&q=80', 'Sérum SPF 50 Tube', 1),
  ('p7', 'https://images.unsplash.com/photo-1584297091622-af8964893796?auto=format&fit=crop&w=800&q=80', 'Bonnet Satin XL', 1),
  ('p8', 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80', 'Brosse Démêlante Flex', 1),
  ('p9', 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=800&q=80', 'Crème Définition Boucles', 1),
  ('p10', 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80', 'Sérum Niacinamide Taches', 1),
  ('p11', 'https://images.unsplash.com/photo-1517677208171-0bc6725a3e60?auto=format&fit=crop&w=800&q=80', 'Kit Kids Douceur', 1),
  ('p12', 'https://images.unsplash.com/photo-1589156280159-27698a70f29e?auto=format&fit=crop&w=800&q=80', 'Kit Protective Style Braids', 1),
  ('p13', 'https://images.unsplash.com/photo-1507152832244-10d45c7eda57?auto=format&fit=crop&w=800&q=80', 'Baume Rasage Barbe', 1),
  ('p14', 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=800&q=80', 'Eadem Milk Marvel Serum', 1),
  ('p15', 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=800&q=80', 'Black Girl Sunscreen SPF 30', 1),
  ('p16', 'https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=800&q=80', 'Taie d’Oreiller 100% Soie', 1);

-- 6. PRODUCT VARIANTS SEED
INSERT INTO public.product_variants (product_id, name, sku, price, stock_quantity) VALUES
  ('p1', 'Format Standard 250ml', 'SKU-P1-250ML', 18.90, 100),
  ('p2', 'Flacon Pompe 300ml', 'SKU-P2-300ML', 14.90, 100),
  ('p3', 'Pot Poids Brut 250g', 'SKU-P3-250G', 24.90, 80),
  ('p4', 'Flacon Spray 150ml', 'SKU-P4-150ML', 16.90, 120),
  ('p5', 'Flacon Pipette 50ml', 'SKU-P5-50ML', 15.90, 90),
  ('p6', 'Tube Airless 50ml', 'SKU-P6-50ML', 22.90, 150),
  ('p7', 'Taille XL Noir Bonnet', 'SKU-P7-XL', 12.90, 200),
  ('p8', 'Brosse Ergonomique Flex', 'SKU-P8-STD', 9.90, 150),
  ('p9', 'Pot Poids Brut 200g', 'SKU-P9-200G', 17.90, 110),
  ('p10', 'Flacon Pipette 30ml', 'SKU-P10-30ML', 29.90, 75),
  ('p11', 'Coffret Cadeau Kids', 'SKU-P11-KIT', 49.00, 60),
  ('p12', 'Kit Complete Protective Trio', 'SKU-P12-KIT', 52.00, 80),
  ('p13', 'Pot Grooming 75ml', 'SKU-P13-75ML', 19.90, 95),
  ('p14', 'Flacon Pompe 30ml', 'SKU-P14-30ML', 62.00, 50),
  ('p15', 'Tube Souple 89ml', 'SKU-P15-89ML', 24.90, 140),
  ('p16', 'Format Standard 65x65cm', 'SKU-P16-STD', 34.90, 100);

-- 7. INVENTORY SEED
INSERT INTO public.inventory (product_id, quantity, reserved_quantity) VALUES
  ('p1', 100, 0),
  ('p2', 100, 0),
  ('p3', 80, 0),
  ('p4', 120, 0),
  ('p5', 90, 0),
  ('p6', 150, 0),
  ('p7', 200, 0),
  ('p8', 150, 0),
  ('p9', 110, 0),
  ('p10', 75, 0),
  ('p11', 60, 0),
  ('p12', 80, 0),
  ('p13', 95, 0),
  ('p14', 50, 0),
  ('p15', 140, 0),
  ('p16', 100, 0);

-- VERIFICATION QUERY
SELECT COUNT(*) FROM public.products;
